version: '3.7'
services:
 agem-dev:
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
   - 9898:80
  volumes:
   - ./code-dev:/var/www
   - ./code-dev/public:/var/www/html
  networks:
   agem_dev_net:
    ipv4_address: 179.22.100.27
volumes:
 code-qa:
networks:
 agem_dev_net:
  driver: bridge
  ipam:
   driver: default
   config:
    -
     subnet: 179.22.100.0/24
